# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install meson ninja
    - uses: ilammy/msvc-dev-cmd@v1 
    - name: Meta-Build (meson)
      if: ${{ matrix.platform != 'windows-latest' }}
      run: |
        meson bin
    - name: Meta-Build (meson)
      if: ${{ matrix.platform == 'windows-latest' }}
      env:
        CC: cl
      run: |
        meson bin
    - name: Build (ninja)
      run: ninja -C bin
    - name: Run tests
      run: ninja -C bin test
